// Display translations only. The Japanese source names remain stable in saved records.
{TEXT("時計広場"), TEXT("Clock Plaza")},
{TEXT("冷たい水"), TEXT("Cold Water")},
{TEXT("水が冷たい、と誰かが笑った。"), TEXT("Someone laughed at how cold the water was.")},
{TEXT("流れに指をひたしている。隣の誰かにも勧めたらしい。\n返事のかたちは残らず、水面だけが、ふたりぶん揺れた。"), TEXT("Fingers dipped into the current. An invitation, perhaps, to someone beside them.\nNo trace of the reply remains. Only the water stirred for two.")},
{TEXT("時計広場の水辺。到着した回廊を、時計に向かって少し進む。"), TEXT("At the water beside Clock Plaza. Follow the arrival walkway a little farther toward the clock.")},
{TEXT("冷めるまで"), TEXT("Before It Grows Cold")},
{TEXT("まだ、ここに"), TEXT("Still Here")},
{TEXT("栞のかわり"), TEXT("In Place of a Bookmark")},
{TEXT("遠い橋の名前"), TEXT("The Name of a Distant Bridge")},
{TEXT("額の外の光"), TEXT("Light Beyond the Frame")},
{TEXT("新しい葉"), TEXT("A New Leaf")},
{TEXT("向かいのカップには、まだ触れていない。"), TEXT("The cup across the table remains untouched.")},
{TEXT("出発の時間を、もう一度たしかめる。"), TEXT("Checking the departure time once more.")},
{TEXT("読みかけの頁を、細い指で押さえている。"), TEXT("Slender fingers hold a half-read page.")},
{TEXT("地図にない橋を、ふたりで指さした。"), TEXT("Together, they pointed to a bridge missing from the map.")},
{TEXT("絵より先に、床の光を見ていた。"), TEXT("Before the painting, it was the light on the floor they noticed.")},
{TEXT("小さな葉を見つけ、誰かを呼びかけた。"), TEXT("Finding a tiny leaf, they called to someone.")},
{TEXT("カップを手のひらで包む。もう一つは向かいの席に。\n飲み終わるまでには、来ると思っていたのだろう。"), TEXT("Hands cradle a cup. Another waits across the table.\nPerhaps they thought the other person would arrive before the last sip.")},
{TEXT("椅子の端に腰かけて、かばんを足元へ寄せる。\n列車が通るたびに顔を上げ、また、窓の外へ目を戻した。"), TEXT("Perched on the edge of a chair, they draw a bag closer to their feet.\nEach passing train makes them look up, then turn back to the window.")},
{TEXT("薄い紙片が見つからず、糸を一本はさんだ。\n明日も同じ頁から。そのつもりで、本を閉じた。"), TEXT("Unable to find a scrap of paper, they slipped a thread between the pages.\nTomorrow, from this same page. With that intention, they closed the book.")},
{TEXT("橋の名前は、ふたりで違っていた。\nどちらが正しいとも決めず、次の休みに行こうと話した。"), TEXT("Each of them had a different name for the bridge.\nWithout deciding who was right, they agreed to go on their next day off.")},
{TEXT("床を横切る四角い光が、少しずつ傾いていく。\n絵を見る時間より長く、その端を目で追っていた。"), TEXT("A square of light slowly tilts across the floor.\nThey followed its edge for longer than they spent looking at the painting.")},
{TEXT("昨日まではなかった葉を見つける。\nかがんで水を足し、誰かに知らせようと振り返った。"), TEXT("A leaf that was not there yesterday.\nThey stooped to add water, then turned to tell someone.")},
{TEXT("雲上ホテル 101"), TEXT("Cloud Hotel 101")},
{TEXT("明日の窓"), TEXT("Tomorrow's Window")},
{TEXT("カーテンを少しだけ開けておく。"), TEXT("Leaving the curtains open just a little.")},
{TEXT("明日の朝、光で目が覚めるように。\n窓辺に置いた一脚の椅子は、街のほうを向いていた。"), TEXT("So that tomorrow's light would wake them.\nA single chair by the window faced the city.")},
{TEXT("時計広場駅の昇降機で上層線へ。雲上ホテル駅で降り、客室階の 101 凪の和邸へ。"), TEXT("Take the Clock Plaza elevator to the Upper Line. Leave at Cloud Hotel, then find room 101, Stillwater Suite, on the guest-room floor.")},
{TEXT("時計広場駅"), TEXT("Clock Plaza Station")},
{TEXT("一本あとで"), TEXT("The Next Train")},
{TEXT("開いた扉の前で、足を止めた。"), TEXT("They stopped before the open doors.")},
{TEXT("列車の扉が閉まる。乗り遅れたのではないらしい。\n誰かの来る回廊を見ながら、次を待つことにした。"), TEXT("The train doors close. It seems they did not miss it.\nWatching the walkway where someone might appear, they chose to wait for the next.")},
{TEXT("時計広場駅の水都線ホーム。東側の昇降機から上がる。"), TEXT("The Water City Line platform at Clock Plaza Station. Take the elevator on the east side.")},
{TEXT("白塔の水都"), TEXT("White Tower Water City")},
{TEXT("水音の数え方"), TEXT("Counting the Sound of Water")},
{TEXT("滝の音に、別の音を探している。"), TEXT("Listening for another sound within the waterfall.")},
{TEXT("同じ水音にも、いくつも層があると言った。\n目を閉じて教えようとした、その先は残っていない。"), TEXT("They said even a single sound of water holds many layers.\nThey closed their eyes to explain. Nothing beyond that remains.")},
{TEXT("時計広場駅の水都線で終点へ。昇降機で水都に降り、中央の聖堂側の広場へ。"), TEXT("Take the Water City Line from Clock Plaza to the last stop. Descend by elevator, then head to the plaza beside the central sanctuary.")},
{TEXT("天空シアター"), TEXT("Sky Theatre")},
{TEXT("上映が終わっても"), TEXT("After the Film")},
{TEXT("画面が暗くなったあとも、座っていた。"), TEXT("They stayed seated after the screen went dark.")},
{TEXT("もう一度見たい場面を、言葉にしようとしている。\nでも、先に風が吹いた。しばらくは、それだけでよかった。"), TEXT("Trying to find words for a scene they wanted to see again.\nBut the wind came first. For a while, that was enough.")},
{TEXT("上層線の天空シアター駅から昇降機で屋上へ。客席の外側の回廊。"), TEXT("From Sky Theatre Station on the Upper Line, take the elevator to the roof. Look along the walkway outside the seating area.")},
{TEXT("アウレリア空中港"), TEXT("Aurelia Skyport")},
{TEXT("見送る手"), TEXT("A Hand in Farewell")},
{TEXT("見えなくなるまで、手を下ろさなかった。"), TEXT("They kept waving until it was out of sight.")},
{TEXT("船の窓は、もう小さな点になっている。\nそれでも手を振り、やがて、手すりにそっと置いた。"), TEXT("The ship's windows have dwindled to tiny dots.\nStill they wave, then gently rest their hand upon the rail.")},
{TEXT("上層線のアウレリア空中港駅から展望桟橋へ。乗船口の手前。"), TEXT("From Aurelia Skyport Station on the Upper Line, head to the observation pier, just before the boarding gate.")},
{TEXT("最後の包み"), TEXT("The Last Parcel")},
{TEXT("風にめくれた頁"), TEXT("A Page Turned by the Wind")},
{TEXT("城の食卓"), TEXT("A Table in the Castle")},
{TEXT("包みの端を、もう一度折り直す。"), TEXT("Folding the edge of a parcel once more.")},
{TEXT("頁が戻るたび、同じ行を読んでいる。"), TEXT("Each time the page turns back, they read the same line.")},
{TEXT("向かいの椅子を、少し引いた。"), TEXT("They pulled the opposite chair out a little.")},
{TEXT("店先で、小さな包みを渡そうとしていた。\n贈る相手のことを聞かれたのか、かすかに肩が動いた。"), TEXT("At the shopfront, they were about to hand over a small parcel.\nPerhaps someone asked who it was for; their shoulders moved ever so slightly.")},
{TEXT("石の回廊には、風の通り道がある。\n本を閉じずに手を離し、遠くから来る足音を待っていた。"), TEXT("The wind has its own path through the stone cloister.\nThey let go of the open book and waited for footsteps in the distance.")},
{TEXT("大きな城の片隅に、ふたりぶんの席。\n一つの皿を真ん中へ寄せる。その小さな距離だけが残った。"), TEXT("In a corner of the great castle, two places at a table.\nA plate moved toward the middle. Only that small distance remains.")},
{TEXT("白い浮遊都市"), TEXT("The White Floating City")},
{TEXT("巨大樹の庭園"), TEXT("Garden of Giant Trees")},
{TEXT("結晶の荒野"), TEXT("Crystal Wastes")},
{TEXT("風時計の塔"), TEXT("Windclock Tower")},
{TEXT("回廊書庫"), TEXT("Corridor Archives")},
{TEXT("空の港"), TEXT("Harbour in the Sky")},
{TEXT("樹冠の展望台"), TEXT("Canopy Lookout")},
{TEXT("古木の祠"), TEXT("Old Tree Shrine")},
{TEXT("光る池"), TEXT("Luminous Pool")},
{TEXT("巨大晶柱"), TEXT("Great Crystal Spire")},
{TEXT("晶洞"), TEXT("Crystal Grotto")},
{TEXT("環状列石"), TEXT("Standing Stone Circle")},
{TEXT("雲を渡る風を数える時計。影が回廊を横切り、遠くの橋へ旅人を誘う。"), TEXT("A clock that counts the wind crossing the clouds. Its shadow travels along the walkway, drawing wanderers toward a distant bridge.")},
{TEXT("空の航路と、まだ名のない土地の記録を収めた書庫。開いた窓から光が落ちる。"), TEXT("Archives of sky routes and lands still without names. Light falls through an open window.")},
{TEXT("浮遊する島々を結ぶ小さな港。船の下には、どこまでも雲海が続いている。"), TEXT("A small harbour linking the floating islands. Beneath the ships, an endless ocean of clouds.")},
{TEXT("葉の天蓋と同じ高さに伸びた見晴らしの場所。枝の向こうに次の道が見える。"), TEXT("A lookout level with the canopy of leaves. Beyond the branches, another path comes into view.")},
{TEXT("太い根の内側に守られた祠。誰かが磨いた石段に、木漏れ日が揺れている。"), TEXT("A shrine sheltered by thick roots. Dappled sunlight shifts across stone steps once polished by someone's hands.")},
{TEXT("古木の根元で静かに光をたたえる池。水辺の花が、道の縁を照らしている。"), TEXT("A quietly glowing pool at the foot of an old tree. Flowers beside the water light the edges of the path.")},
{TEXT("遠くからも目印になる結晶の柱。層になった色が空の光を映している。"), TEXT("A crystal pillar visible from far away. Its layered colours catch the light of the sky.")},
{TEXT("岩に包まれた結晶の空洞。入口をくぐると、外の風景が額縁のように見える。"), TEXT("A crystal hollow enclosed in rock. From inside, the entrance frames the world beyond.")},
{TEXT("荒野に並ぶ石の輪。隙間の向こうに、別の島と細い回廊が重なって見える。"), TEXT("A ring of stones in the wilderness. Through the gaps, another island and a slender walkway overlap in the distance.")},
{TEXT("白塔の水都・西の入口"), TEXT("Water City — West Entrance")},
{TEXT("白塔の水都・滝見の回廊"), TEXT("Water City — Cascade Walk")},
{TEXT("白塔の水都・水鏡の聖堂"), TEXT("Water City — Mirrorwater Sanctuary")},
{TEXT("蔦の絡む石の回廊を上がると、重なる水面、白い尖塔と滝が見渡せる。東へ向かうほど水盤は一段ずつ低くなる。"), TEXT("Climb the ivy-covered stone walkway for views of layered pools, white spires and waterfalls. Each pool steps down farther to the east.")},
{TEXT("都市の東の外縁に広がる水の街。開いた石の聖堂を抜け、橋の下の柱や水底の遺構を探してみよう。"), TEXT("A city of water beyond the eastern outskirts. Walk through its open stone sanctuary and look for pillars beneath the bridges and ruins under the water.")},
{TEXT("水庭のカフェ"), TEXT("Water Garden Cafe")},
{TEXT("雲待ちのラウンジ"), TEXT("Cloudwatch Lounge")},
{TEXT("空の大図書館"), TEXT("Grand Sky Library")},
{TEXT("旅の地図室"), TEXT("Traveller's Map Room")},
{TEXT("光の美術館"), TEXT("Gallery of Light")},
{TEXT("硝子の植物園"), TEXT("Glass Conservatory")},
{TEXT("街の公共施設"), TEXT("City Landmark")},
{TEXT("水盤と木のカウンターを囲む喫茶室。窓際に座り、回廊を行き交う景色を眺める。"), TEXT("A cafe around a pool and a wooden counter. Sit by the window and watch the walkways beyond.")},
{TEXT("布の天蓋、柔らかな椅子、静かな水面。散策の合間に立ち寄る空の休憩所。"), TEXT("Fabric canopies, soft chairs and still water. A resting place in the sky between walks.")},
{TEXT("高さ18mの吹き抜けと壁を埋める本棚。階段の先の閲覧回廊から、書庫全体を見渡せる。"), TEXT("An 18-metre atrium with walls lined in books. Climb to the reading gallery for a view of the entire library.")},
{TEXT("まだ名のない島々の模型と、大きな地図のある書斎。都市を小さく見つめ直す場所。"), TEXT("A study holding a large map and models of unnamed islands. A place to see the great city on a smaller scale.")},
{TEXT("白い展示壁を巡り、色の風景画や金属の彫刻に出会う。街の光も展示の一部になる美術館。"), TEXT("Follow white exhibition walls past colourful landscapes and metal sculptures. The city's own light becomes part of the collection.")},
{TEXT("ステンレスの斜めの柱と大きなガラス壁。緑と水、都市の風景を重ねる空中植物園。"), TEXT("Slanted stainless-steel columns and great glass walls. A hanging conservatory that layers greenery and water over the city beyond.")},
{TEXT("時計広場から南西の塔へ・広場と同じ階"), TEXT("The southwest tower from Clock Plaza, on the same level.")},
{TEXT("カフェの塔の昇降機で、カフェから1つ上の停車階へ"), TEXT("Take the cafe tower's elevator one stop above the cafe.")},
{TEXT("広場の南東の塔・昇降機の「空の大図書館」へ"), TEXT("In the southeast tower, choose Grand Sky Library in the elevator.")},
{TEXT("大図書館の塔で、さらに1つ上の停車階へ"), TEXT("In the library tower, take the elevator one more stop upward.")},
{TEXT("映画館の塔・昇降機の「光の美術館」へ"), TEXT("In the cinema tower, choose Gallery of Light in the elevator.")},
{TEXT("美術館の塔で、さらに1つ上の停車階へ"), TEXT("In the gallery tower, take the elevator one more stop upward.")},
{TEXT("凪の和邸"), TEXT("Stillwater Suite")},
{TEXT("雲のギャラリー"), TEXT("Cloud Gallery")},
{TEXT("水庭のサロン"), TEXT("Water Garden Salon")},
{TEXT("琥珀のオアシス"), TEXT("Amber Oasis")},
{TEXT("真珠のサロン"), TEXT("Pearl Salon")},
{TEXT("夜景の書斎"), TEXT("Nightfall Study")},
{TEXT("光彩のロフト"), TEXT("Prismatic Loft")},
{TEXT("湖雲のロッジ"), TEXT("Cloudlake Lodge")},
{TEXT("上層レジデンス"), TEXT("Upper Residences")},
{TEXT("木の湯船、障子、畳の読書席。静かな和のスイート。"), TEXT("A wooden bath, paper screens and a tatami reading nook. A quiet Japanese-style suite.")},
{TEXT("暮らしの中に彫刻とアートを置く、緑豊かなギャラリー。"), TEXT("A lush gallery where sculpture and art become part of everyday life.")},
{TEXT("水庭と木の格子、深い緑。リゾートのように過ごす部屋。"), TEXT("A water garden, wooden latticework and deep greenery. A room for a resort-like escape.")},
{TEXT("砂色の石と天蓋、琥珀色の灯りに包まれる隠れ家。"), TEXT("A retreat of sandstone, canopies and warm amber light.")},
{TEXT("真珠色の壁と細い金の装飾、シャンデリアのサロン。"), TEXT("Pearlescent walls, delicate gold trim and a chandelier-lit salon.")},
{TEXT("濃い木、本棚、暖炉。都市の夜景と読書を楽しむ部屋。"), TEXT("Dark wood, bookshelves and a fireplace. A room for reading beside the city's nightscape.")},
{TEXT("立体的な窓枠と鮮やかな織物。光とアートのロフト。"), TEXT("Sculpted window frames and vivid textiles. A loft filled with light and art.")},
{TEXT("梁のある天井、石の暖炉、雲を望む山荘のリビング。"), TEXT("Exposed beams, a stone fireplace and a mountain-lodge living room overlooking clouds.")},
{TEXT("円環商店街"), TEXT("Ringmarket")},
{TEXT("雲上の回廊院"), TEXT("Cloudborne Cloister")},
{TEXT("空に眠る城"), TEXT("Castle Asleep in the Sky")},
{TEXT("水都駅の昇降機で広場へ。北側の滝見の回廊を上がり、左のガラス塔へ。"), TEXT("Descend from Water City Station to the plaza. Climb the northern Cascade Walk, then enter the glass tower on your left.")},
{TEXT("円環商店街のある広場から橋を東へ一つ渡る。北の滝見の回廊にある昇降機で「雲上の回廊院」へ。"), TEXT("Cross one bridge east from the Ringmarket plaza. On the northern Cascade Walk, take the elevator to Cloudborne Cloister.")},
{TEXT("回廊院の広場から東へ一つ、さらに北へ一つ橋を渡る。滝見の回廊の奥の昇降機で「空に眠る城」へ。"), TEXT("From the cloister plaza, cross one bridge east and another north. At the far end of Cascade Walk, take the elevator to Castle Asleep in the Sky.")},
{TEXT("水都・滝見の回廊"), TEXT("Water City — Cascade Walk")},
{TEXT("雲上ホテル"), TEXT("Cloud Hotel")},
{TEXT("上層線 / ホテル・シアター・空港"), TEXT("Upper Line / Hotel · Theatre · Skyport")},
{TEXT("水都線 / 時計広場・白塔の水都"), TEXT("Water City Line / Clock Plaza · Water City")},
{TEXT("居間"), TEXT("Living Room")},
{TEXT("寝室"), TEXT("Bedroom")},
{TEXT("書斎"), TEXT("Study")},
{TEXT("食堂"), TEXT("Dining Room")},
{TEXT("図書館"), TEXT("Library")},
{TEXT("雨継ぎの窓辺"), TEXT("Rainlight Window")},
{TEXT("水辺の喫茶室"), TEXT("Waterside Cafe")},
{TEXT("植物の温室"), TEXT("Greenhouse")},
{TEXT("画家のアトリエ"), TEXT("Painter's Studio")},
{TEXT("音楽室"), TEXT("Music Room")},
{TEXT("水鏡の映写室"), TEXT("Mirrorwater Cinema")},
{TEXT("広場のモニター"), TEXT("Plaza Screen")},
{TEXT("部屋"), TEXT("Room")},
{TEXT("天空の客席"), TEXT("Sky Theatre Seat")},
{TEXT("ソラメダカ"), TEXT("Cloud Minnow")},
{TEXT("白い街の水路に群れる小さな魚。水面の雲を追いかける。"), TEXT("A tiny fish that schools in the white city's canals, chasing clouds reflected on the water.")},
{TEXT("銀雲ブナ"), TEXT("Silvercloud Bream")},
{TEXT("雲が流れるように、ゆっくりと水庭を巡る。"), TEXT("Drifts through the water garden as slowly as a passing cloud.")},
{TEXT("時計ゴイ"), TEXT("Clockwork Koi")},
{TEXT("時計広場の主。金色の尾を見つけると良い一日になる。"), TEXT("The guardian of Clock Plaza. Spotting its golden tail is said to bring a good day.")},
{TEXT("花びらウオ"), TEXT("Petalfish")},
{TEXT("朝の水庭に浮かぶ花びらのような、淡い桃色の魚。"), TEXT("A pale pink fish like a petal floating through the morning water garden.")},
{TEXT("ガラスマス"), TEXT("Glass Trout")},
{TEXT("滝の冷たい水を好む。青く澄んだ鱗が陽にきらめく。"), TEXT("Prefers the cool water near the falls. Clear blue scales shimmer in sunlight.")},
{TEXT("水路スズキ"), TEXT("Canal Perch")},
{TEXT("南の流れで育つ力強い魚。石橋の影が休み場所。"), TEXT("A strong fish from the southern current, resting in the shade of stone bridges.")},
{TEXT("夕焼けコイ"), TEXT("Sunset Carp")},
{TEXT("夕方だけ、朱色のひれが水面を染める。"), TEXT("Only at dusk do its vermilion fins colour the water.")},
{TEXT("灯りテトラ"), TEXT("Lantern Tetra")},
{TEXT("街灯がともるころ現れる。小さな金の粒のよう。"), TEXT("Appears as the streetlights come on, like a tiny speck of gold.")},
{TEXT("月影エンゼル"), TEXT("Moonshadow Angelfish")},
{TEXT("夜の水庭にひそむ銀色の魚。長いひれが月を映す。"), TEXT("A silver fish hiding in the water garden at night. Its long fins reflect the moon.")},
{TEXT("星屑ナマズ"), TEXT("Stardust Catfish")},
{TEXT("静かな南水路の底にいる。星が出るころ活動を始める。"), TEXT("Lives on the quiet bed of the southern canal and stirs when the stars appear.")},
{TEXT("雨糸ウナギ"), TEXT("Rainribbon Eel")},
{TEXT("朝夕の細い流れを縫うように泳ぐ、リボンのような魚。"), TEXT("A ribbon-like fish weaving through narrow currents at dawn and dusk.")},
{TEXT("オーロラフィッシュ"), TEXT("Aurora Fish")},
{TEXT("夜明けと深夜、ごくまれに水面を虹色に照らす。"), TEXT("On rare occasions at dawn or midnight, it lights the water in rainbow colours.")},
{TEXT("時計広場の水辺"), TEXT("Clock Plaza Waterfront")},
{TEXT("時計広場の南側。低い手すりに沿って、釣りの看板へ。"), TEXT("South of Clock Plaza. Follow the low railing to the fishing sign.")},
{TEXT("北の水庭"), TEXT("Northern Water Garden")},
{TEXT("北の昇降機で水庭の階へ。滝を眺める渡り廊下の先。"), TEXT("Take the northern elevator to the water garden, then cross the walkway overlooking the falls.")},
{TEXT("南の水路"), TEXT("Southern Canal")},
{TEXT("時計広場から南の回廊をまっすぐ。南端の滝の手前にある釣りの看板へ。"), TEXT("Follow the southern walkway straight from Clock Plaza to the fishing sign before the waterfall.")},
{TEXT("いつでも"), TEXT("Any time")},
{TEXT("朝"), TEXT("Morning")},
{TEXT("昼"), TEXT("Day")},
{TEXT("夕"), TEXT("Evening")},
{TEXT("夜"), TEXT("Night")},
{TEXT("すべての水辺"), TEXT("All fishing spots")},
{TEXT("空の回廊  /  ENDLESS WORLD"), TEXT("SKY CORRIDOR  /  ENDLESS WORLD")},
{TEXT("水は、まだ流れている。　Q / 右スティック押込み：記録端末を持ち上げる"), TEXT("The water still flows.  Q / Press right stick: raise your memory device")},
{TEXT("友人機能は開発中です。この公開版では利用できません。"), TEXT("Friends is in development and unavailable in this public build.")},
{TEXT("観測中　近づいて静かに眺め、E で記録する。Q で端末。"), TEXT("Observing  Approach and watch quietly. E: record. Q: device.")},
{TEXT("観測を終えました。"), TEXT("Observation ended.")},
{TEXT("もう少しそばで、静かに眺めてみる。"), TEXT("Stay nearby and watch quietly for a moment longer.")},
{TEXT("記録を保存できません。"), TEXT("Unable to save this memory.")},
{TEXT("端末に残しました　「"), TEXT("Saved to your device: “")},
{TEXT("」　Q で読む"), TEXT("”  Q: read")},
{TEXT("　Q 記録を読む"), TEXT("  Q: read memory")},
{TEXT("　E 端末に記録する"), TEXT("  E: record on device")},
{TEXT("　そばで、少し眺めてみる"), TEXT("  Stay nearby and watch for a moment")},
{TEXT("正面"), TEXT("Ahead")},
{TEXT("後方"), TEXT("Behind you")},
{TEXT("右手"), TEXT("To your right")},
{TEXT("左手"), TEXT("To your left")},
{TEXT("%s　直線で約 %.0f m\n%s\n\n%s"), TEXT("%s  About %.0f m in a straight line\n%s\n\n%s")},
{TEXT("今いる場所より上の階です。昇降機を利用してください。"), TEXT("On a higher floor. Use an elevator.")},
{TEXT("今いる場所より下の階です。"), TEXT("On a lower floor.")},
{TEXT("ほぼ同じ高さにあります。"), TEXT("At roughly the same height.")},
{TEXT("展望昇降機　移動中…"), TEXT("Panoramic elevator  Moving…")},
{TEXT("展望昇降機　行き先の階を選ぶ"), TEXT("Panoramic elevator  Choose a floor")},
{TEXT("　開いたかごへ進む"), TEXT("  Enter the open cabin")},
{TEXT("　この階へ呼ぶ"), TEXT("  Call to this floor")},
{TEXT("展望昇降機　かごの中央へ進む"), TEXT("Panoramic elevator  Move to the centre of the cabin")},
{TEXT("展望昇降機　この階へ呼ぶ"), TEXT("Panoramic elevator  Call to this floor")},
{TEXT("展望昇降機："), TEXT("Panoramic elevator: ")},
{TEXT("出発広場　地上連絡路"), TEXT("Arrival Plaza — Ground Walkway")},
{TEXT("月凪 / TSUKINAGI"), TEXT("TSUKINAGI / Moon Calm")},
{TEXT("白鷺 / SHIRASAGI"), TEXT("SHIRASAGI / White Heron")},
{TEXT("　寄港中・出港まで %d 秒　乗り口から下船できます"), TEXT("  Docked · Departure in %d s · Disembark through the boarding door")},
{TEXT("　都市遊覧中　船内を自由に歩けます / 階段から上部プールデッキへ"), TEXT("  Cruising over the city · Explore the cabin / Take the stairs to the pool deck")},
{TEXT("　乗船できます"), TEXT("  Boarding open")},
{TEXT("　乗船橋を操作中"), TEXT("  Boarding bridge moving")},
{TEXT("\n出港まで %d 秒　橋を渡って船内へ"), TEXT("\nDeparture in %d s · Cross the bridge to board")},
{TEXT("AURELIA SKYPORT\n次の遊覧船："), TEXT("AURELIA SKYPORT\nNext sky yacht: ")},
{TEXT("\n到着まで 約 %d 秒　ゲートの手前でお待ちください"), TEXT("\nArrival in about %d s · Please wait before the gate")},
{TEXT("　雲を望む上層の客室"), TEXT("  An upper suite overlooking the clouds")},
{TEXT("　32席の小さな映画館"), TEXT("  An intimate 32-seat cinema")},
{TEXT("　空の見える閲覧室"), TEXT("  A reading room open to the sky")},
{TEXT("　このまま歩いて入れます"), TEXT("  Walk inside to enter")},
{TEXT("　回廊へ自由に出入りできます"), TEXT("  Walk freely between the room and corridor")},
{TEXT("101–108号室 → 右の昇降機で客室階へ"), TEXT("Rooms 101–108 → Elevator on the right to guest rooms")},
{TEXT("右の昇降機：上へ 天空シアター / 下へ 時計広場・水都線"), TEXT("Right elevator: up to Sky Theatre / down to Clock Plaza and Water City Line")},
{TEXT("右奥の昇降機 → 最上階・豪華飛行船の搭乗口"), TEXT("Elevator at the rear right → Rooftop and sky yacht boarding")},
{TEXT("右の昇降機 → 上層線（ホテル・シアター・空港）"), TEXT("Right elevator → Upper Line (Hotel · Theatre · Skyport)")},
{TEXT("右の昇降機 → 水鏡の聖堂・水辺の広場"), TEXT("Right elevator → Mirrorwater Sanctuary and Waterfront Plaza")},
{TEXT("駅　"), TEXT(" Station  ")},
{TEXT("次は %s　発車まで %d 秒"), TEXT("Next: %s · Departure in %d s")},
{TEXT("次の電車まで %d 秒"), TEXT("Next train in %d s")},
{TEXT("駅　E / WASD 降りる　マウス 見回す"), TEXT(" Station  E / WASD: leave train · Mouse: look around")},
{TEXT("空中電車　次は "), TEXT("Skyrail  Next: ")},
{TEXT("　マウスで車窓を眺める"), TEXT("  Mouse: enjoy the view")},
{TEXT("駅　空中電車に乗る　E"), TEXT(" Station  E: board skyrail")},
{TEXT("駅　電車を待つ（発車案内はホームの表示板へ）"), TEXT(" Station  Wait for the train (see the platform departure board)")},
{TEXT("走行中です。駅に停車してから降りられます。"), TEXT("The train is moving. You can leave once it stops at a station.")},
{TEXT("電車が到着するまでホームでお待ちください。"), TEXT("Please wait on the platform for the train to arrive.")},
{TEXT("次は "), TEXT("Next: ")},
{TEXT("。まもなく出発します。"), TEXT(". Departing shortly.")},
{TEXT("↑ ホテル・天空シアター・空港\n右の昇降機で『上層線』へ"), TEXT("↑ Hotel · Sky Theatre · Skyport\nRight elevator to the Upper Line")},
{TEXT("時計広場駅\n水都線・上層線　この昇降機から"), TEXT("CLOCK PLAZA STATION\nWater City and Upper Lines via this elevator")},
{TEXT("↑ 天空シアター　↓ 時計広場・水都線\n右の昇降機で行き先を選ぶ"), TEXT("↑ Sky Theatre  ↓ Clock Plaza · Water City Line\nChoose a floor in the right elevator")},
{TEXT("雲上ホテル\n← 107・108　　　103・104 →"), TEXT("CLOUD HOTEL\n← 107 · 108     103 · 104 →")},
{TEXT("雲上ホテル\n← 105・106　　　101・102 →"), TEXT("CLOUD HOTEL\n← 105 · 106     101 · 102 →")},
{TEXT("アウレリア空中港\nこの昇降機で『搭乗口』へ"), TEXT("AURELIA SKYPORT\nTake this elevator to Boarding")},
{TEXT("撮影が完了しませんでした。もう一度お試しください。"), TEXT("The photo could not be completed. Please try again.")},
{TEXT("別の撮影が進行中です。少し待ってからお試しください。"), TEXT("Another photo is being taken. Please wait and try again.")},
{TEXT("写真の保存先を開けません。"), TEXT("Unable to open the photo folder.")},
{TEXT("写真の保存先を作成できません。"), TEXT("Unable to create the photo folder.")},
{TEXT("写真を保存しています…"), TEXT("Saving photo…")},
{TEXT("写真を保存しました。Screenshots フォルダーから開けます。"), TEXT("Photo saved. Open it from the Screenshots folder.")},
{TEXT("写真は保存済みです。撮影場所の記録は保存できませんでした。"), TEXT("Photo saved, but its location could not be recorded.")},
{TEXT("写真を保存できませんでした。空き容量を確認してください。"), TEXT("Unable to save the photo. Check your free disk space.")},
{TEXT("%d 秒後に撮影"), TEXT("Photo in %d s")},
{TEXT("FISHING  /  釣り場"), TEXT("FISHING SPOT")},
{TEXT("水を眺めて、ひと休み。"), TEXT("Watch the water. Stay a while.")},
{TEXT("釣りは一人での散策で遊べます。街での釣りは接続確認後に対応します。"), TEXT("Fishing is available in solo exploration. Online fishing is still in development.")},
{TEXT("浮きが沈んだら、もう一度 "), TEXT("When the float sinks, press ")},
{TEXT("。連打は不要です。"), TEXT(" once more. No rapid tapping needed.")},
{TEXT("水面を眺めながら、魚を待つ…　歩くと中断"), TEXT("Watching the water, waiting for a fish…  Move to cancel")},
{TEXT("浮きが沈んだ！　"), TEXT("The float sank!  ")},
{TEXT(" を一度押して引き上げる"), TEXT(": press once to reel in")},
{TEXT("魚をゆっくり引き寄せています…"), TEXT("Gently reeling in the fish…")},
{TEXT("釣果を見る　"), TEXT("View catch  ")},
{TEXT("　釣りをする　"), TEXT("  Fish  ")},
{TEXT("魚は水へ戻っていきました。また竿を出せます。"), TEXT("The fish slipped back into the water. You can cast again.")},
{TEXT("浮きが沈みました！　一度だけ "), TEXT("The float sank! Press ")},
{TEXT(" を押してください。"), TEXT(" once.")},
{TEXT("天空シアター\n\n入口の光る端末で上映を選ぶ"), TEXT("SKY THEATRE\n\nChoose a film at the glowing tablet by the entrance")},
{TEXT("水鏡の映写室\n\nロビーの光る端末で上映を選ぶ"), TEXT("MIRRORWATER CINEMA\n\nChoose a film at the glowing tablet in the lobby")},
{TEXT("空の回廊 シネマ\n\n広場の光る端末で YouTubeを探す"), TEXT("SKY CORRIDOR CINEMA\n\nFind YouTube videos at the glowing tablet in the plaza")},
{TEXT("の光る端末に近づいて操作してください。"), TEXT(": move closer to its glowing tablet to use it.")},
{TEXT("101 凪の和邸\n102 雲のギャラリー"), TEXT("101 Stillwater Suite\n102 Cloud Gallery")},
{TEXT("103 水庭のサロン\n104 琥珀のオアシス"), TEXT("103 Water Garden Salon\n104 Amber Oasis")},
{TEXT("105 真珠のサロン\n106 夜景の書斎"), TEXT("105 Pearl Salon\n106 Nightfall Study")},
{TEXT("107 光彩のロフト\n108 湖雲のロッジ"), TEXT("107 Prismatic Loft\n108 Cloudlake Lodge")},
{TEXT("この世界コードの形式・生成器・素材の版には対応していません。ew2-kit1 のコードを入力してください。"), TEXT("This world-code format, generator or asset version is unsupported. Enter an ew2-kit1 code.")},
{TEXT("世界番号は半角の小文字・数字32文字で指定してください。"), TEXT("The world ID must contain 32 lowercase letters and digits.")},
{TEXT("区画データの範囲が不正です"), TEXT("Invalid district data bounds")},
{TEXT("形状の座標が不正です"), TEXT("Invalid geometry coordinates")},
{TEXT("室内の配置が不正です"), TEXT("Invalid interior layout")},
{TEXT("窓辺の部屋の仕様が不正です"), TEXT("Invalid window-room specification")},
{TEXT("水都の範囲が不正です"), TEXT("Invalid Water City bounds")},
{TEXT("水都の配置定義が不正です"), TEXT("Invalid Water City layout")},
{TEXT("水辺の道の仕様が不正です"), TEXT("Invalid waterside path specification")},
{TEXT("道の幅・勾配が範囲外です"), TEXT("Path width or slope is out of range")},
{TEXT("境界の道が接続されていません"), TEXT("Paths are not connected at the district boundary")},
{TEXT("場所コードが長すぎます。"), TEXT("The location code is too long.")},
{TEXT("場所コードの形式が違います。"), TEXT("Invalid location-code format.")},
{TEXT("場所コードが途中で変わっています。もう一度コピーしてください。"), TEXT("The location code was altered. Please copy it again.")},
{TEXT("場所の座標が不正です。"), TEXT("Invalid location coordinates.")},
{TEXT("この場所の座標は対応範囲外です。"), TEXT("This location is outside the supported coordinate range.")},
