// Exact, presentation-only translations. Stable save keys stay Japanese.
{TEXT("旅のはじまり"), TEXT("The journey begins")},
{TEXT("展望昇降機が移動しています。"), TEXT("The panoramic lift is moving.")},
{TEXT("昇降機のかごの中央へ進み、行き先を選んでください。"), TEXT("Step into the center of the lift, then choose a destination.")},
{TEXT("この階へ昇降機を呼びました。"), TEXT("The lift has been called to this floor.")},
{TEXT("雨継ぎの窓辺　水音を聞きながら、出発した広場を眺められます。"), TEXT("Raincatcher Window — listen to the water and look back at the plaza where you began.")},
{TEXT("展望昇降機："), TEXT("Panoramic elevator: ")},
{TEXT("へ移動します。"), TEXT(" — departing.")},
{TEXT("かごの中央に立ってから、もう一度行き先を選んでください。"), TEXT("Stand in the center of the lift, then choose your destination again.")},
{TEXT("公開の街では徒歩で移動できます。場所コードでの移動は街を退出してから利用してください。"), TEXT("Walk to explore a public city. Leave the city before using a location code.")},
{TEXT("時計広場駅"), TEXT("Clock Plaza Station")},
{TEXT("天空シアター"), TEXT("Sky Theatre")},
{TEXT("水鏡の映写室"), TEXT("Mirrorwater Cinema")},
{TEXT("発見地点の案内標へ近づくと、旅の図鑑へ記録できます。"), TEXT("Approach a discovery marker to add this place to your journal.")},
{TEXT("この場所は図鑑に記録されています。"), TEXT("This place is already in your journal.")},
{TEXT("発見を記録しました："), TEXT("Discovery recorded: ")},
{TEXT("世界コードをコピーしました。"), TEXT("World code copied.")},
{TEXT("場所コードをコピーしました。同じ版のゲームでこの場所を訪れられます。"), TEXT("Location code copied. Use the same game version to visit this place.")},
{TEXT("発見記録を書き出しました。保存フォルダーの Exports にあります。"), TEXT("Discoveries exported to Exports in your save folder.")},
{TEXT("この機能は開発中です。通常の公開版では利用できません。"), TEXT("This feature is in development and unavailable in the public build.")},
{TEXT("現在地を取得できないため、保存を見送りました。"), TEXT("Your position could not be read, so it was not saved.")},
{TEXT("保存場所を開けないため、現在地を保存できません。"), TEXT("Your position could not be saved because the save folder could not be opened.")},
{TEXT("空の回廊-"), TEXT("SkyCorridor-")},
{TEXT("撮影しました。保存フォルダーの Screenshots から開けます。"), TEXT("Photo saved. Find it in Screenshots in your save folder.")},
{TEXT("メインディスプレイ %d × %d に表示しました。"), TEXT("Moved to the primary display at %d × %d.")},
{TEXT("現在の表示　%d × %d ／ 描画 %.0f%%"), TEXT("Display: %d × %d / Render scale: %.0f%%")},
{TEXT("空の回廊"), TEXT("Sky Corridor")},
{TEXT("白塔の水都"), TEXT("White Tower Water City")},
{TEXT("の光る端末　"), TEXT(" control tablet — ")},
{TEXT("E 操作"), TEXT("E Interact")},
{TEXT("X 操作"), TEXT("X Interact")},
{TEXT("□ 操作"), TEXT("□ Interact")},
{TEXT("チェスの卓　遊ぶ　E"), TEXT("Chess table — Play — E")},
{TEXT("アウレリア空中港　正面の発着案内へ / 寄港中は橋を歩いて乗船"), TEXT("Aurelia Skyport — departures ahead / Walk across the bridge while docked")},
{TEXT("天空シアター　"), TEXT("Sky Theatre — ")},
{TEXT("水鏡の映写室　"), TEXT("Mirrorwater Cinema — ")},
{TEXT("雨継ぎの窓辺　"), TEXT("Raincatcher Window — ")},
{TEXT("E / WASD 立ち上がる　マウス 見回す"), TEXT("E / WASD Stand up   Mouse Look")},
{TEXT("X / 左スティック 立ち上がる　右スティック 見回す"), TEXT("X / Left stick Stand up   Right stick Look")},
{TEXT("□ / 左スティック 立ち上がる　右スティック 見回す"), TEXT("□ / Left stick Stand up   Right stick Look")},
{TEXT("天空シアターの客席　座る　"), TEXT("Sky Theatre seating — Sit — ")},
{TEXT("天空シアター　検索・再生　"), TEXT("Sky Theatre — Search / Play — ")},
{TEXT("映画館の客席　座る　"), TEXT("Cinema seating — Sit — ")},
{TEXT("水鏡の映写室　検索・再生　"), TEXT("Mirrorwater Cinema — Search / Play — ")},
{TEXT("広場のモニター　検索・再生　"), TEXT("Plaza Screen — Search / Play — ")},
{TEXT("WASD 歩く　Shift 走る　Space 2段ジャンプ　Tab 図鑑　Esc メニュー"), TEXT("WASD Walk   Shift Run   Space Double jump   Tab Journal   Esc Menu")},
{TEXT("左スティック 移動　LB 走る　A 2段ジャンプ　Y 図鑑　Menu メニュー"), TEXT("Left stick Move   LB Run   A Double jump   Y Journal   Menu Menu")},
{TEXT("左スティック 移動　L1 走る　× 2段ジャンプ　△ 図鑑　Options メニュー"), TEXT("Left stick Move   L1 Run   × Double jump   △ Journal   Options Menu")},
{TEXT("　記録済み ／ "), TEXT("Recorded / ")},
{TEXT(" 図鑑"), TEXT(" Journal")},
{TEXT(" 発見を記録する"), TEXT(" Record discovery")},
{TEXT("周囲の景色と道を準備しています…"), TEXT("Preparing the surrounding scenery and paths…")},
{TEXT("区画 %d/49　生成 %d/2　待機 %d/8　原点移動 %d\n描画個数 %d　当たり判定 %d　反映 %.2f ms　RAM %.2f GB\n%s"), TEXT("Districts %d/49   Generating %d/2   Queued %d/8   Origin shifts %d\nInstances %d   Colliders %d   Apply %.2f ms   RAM %.2f GB\n%s")},
{TEXT("利用できます"), TEXT("Available")},
{TEXT("GeForce RTXなどの対応GPUが必要です"), TEXT("Requires a supported GPU, such as GeForce RTX")},
{TEXT("NVIDIAドライバーの更新が必要です"), TEXT("Update your NVIDIA driver")},
{TEXT("Windowsの更新が必要です"), TEXT("Update Windows")},
{TEXT("描画キャプチャーツールとの併用に対応していません"), TEXT("Not compatible with an active graphics capture tool")},
{TEXT("この環境では利用できません"), TEXT("Unavailable on this system")},
{TEXT("ネイティブ / TSR"), TEXT("Native / TSR")},
{TEXT("DLAA / 描画100%"), TEXT("DLAA / 100% rendering")},
{TEXT("DLSS クオリティ"), TEXT("DLSS Quality")},
{TEXT("DLSS バランス"), TEXT("DLSS Balanced")},
{TEXT("DLSS パフォーマンス"), TEXT("DLSS Performance")},
{TEXT("DLSS ウルトラパフォーマンス"), TEXT("DLSS Ultra Performance")},
{TEXT("フレーム生成なし"), TEXT("Frame generation off")},
{TEXT("動的マルチフレーム生成"), TEXT("Dynamic multi-frame generation")},
{TEXT("フレーム生成 %d倍"), TEXT("Frame generation %dx")},
{TEXT("対応状況を確認しています…"), TEXT("Checking support…")},
{TEXT("この環境ではレイ再構成を利用できません。"), TEXT("Ray reconstruction is unavailable on this system. ")},
{TEXT("レイ再構成にはハードウェアレイトレーシングが必要です。"), TEXT("Ray reconstruction requires hardware ray tracing.")},
{TEXT("反射や間接光のノイズをAIで再構成します。オンにするとDLSSまたはDLAAと併用します。"), TEXT("Uses AI to reconstruct reflections and indirect lighting. Requires DLSS or DLAA.")},
{TEXT("レイ再構成を開始できなかったため、通常の描画へ戻しました。設定を入れ直すと再試行します。"), TEXT("Ray reconstruction could not start. Standard rendering restored. Toggle the setting to retry.")},
{TEXT("設定はオンです。DLSSまたはDLAAを選ぶと再開します。"), TEXT("Enabled in settings. Select DLSS or DLAA to resume.")},
{TEXT("レイ再構成を設定しました。この構成では内部処理の計測情報を取得できません。"), TEXT("Ray reconstruction configured. Internal processing measurements are unavailable in this build.")},
{TEXT("レイ再構成を開始していません。"), TEXT("Ray reconstruction has not started.")},
{TEXT("レイ再構成：動作中"), TEXT("Ray reconstruction: active")},
{TEXT("レイ再構成の動作を確認しています…"), TEXT("Checking ray reconstruction…")},
{TEXT("この配布版にはレイ再構成が含まれていません。保存済みの設定は保持されます。"), TEXT("Ray reconstruction is not included in this build. Your saved preference is retained.")},
{TEXT("画面の対応状況を確認しています…"), TEXT("Checking display support…")},
{TEXT("設定はオンです。現在の画面ではSDRで表示しています。HDR対応画面へ戻すと再開します。"), TEXT("Enabled in settings. Using SDR on this display. HDR resumes on a supported display.")},
{TEXT("HDR対応画面で、Windowsの「HDRを使用する」をオンにすると利用できます。"), TEXT("On an HDR display, enable Use HDR in Windows settings.")},
{TEXT("HDRを利用できます。明るい水面や空の光を、より広い明るさで表示します。"), TEXT("HDR is available. Water and sky highlights can use a wider brightness range.")},
{TEXT("HDR：動作中"), TEXT("HDR: active")},
{TEXT("HDR表示へ切り替えています…"), TEXT("Switching to HDR…")},
{TEXT("HDR：Unreal Engineで有効（画面出力の直接計測は未対応）"), TEXT("HDR: enabled in Unreal Engine (display output not directly measured)")},
{TEXT("ゲーム描画のFPS上限を設定します。垂直同期と併用できます。"), TEXT("Set the game rendering FPS limit. Can be used with VSync.")},
{TEXT("ゲーム描画のFPS上限を設定します。フレーム生成を使う場合、生成フレームを含む表示FPSの上限は保証されません。"), TEXT("Set the game rendering FPS limit. With frame generation, the total displayed FPS limit is not guaranteed.")},
{TEXT("上限には生成したフレームも含みます。"), TEXT("This limit includes generated frames.")},
{TEXT(" %d倍ではゲーム描画の上限は %.1f FPS です。"), TEXT(" At %dx, the game rendering limit is %.1f FPS.")},
{TEXT("\n動的フレーム生成と垂直同期は併用できません。"), TEXT("\nDynamic frame generation cannot be combined with VSync.")},
{TEXT("\nこの環境はフレーム生成と垂直同期の併用に対応していません。"), TEXT("\nThis system does not support frame generation with VSync.")},
{TEXT("描画機能を確認しています…"), TEXT("Checking graphics features…")},
{TEXT("\nフレーム生成には Windows のハードウェアアクセラレータによるGPUスケジューリングが必要です。"), TEXT("\nFrame generation requires Windows hardware-accelerated GPU scheduling.")},
{TEXT("\nフレーム生成には NVIDIA ドライバーの更新が必要です。"), TEXT("\nFrame generation requires an NVIDIA driver update.")},
{TEXT("\nフレーム生成は DirectX 12 で起動すると利用できます。"), TEXT("\nLaunch with DirectX 12 to use frame generation.")},
{TEXT("\nフレーム生成はこの環境で利用できません。"), TEXT("\nFrame generation is unavailable on this system.")},
{TEXT("\n現在はネイティブ描画を使用しています。"), TEXT("\nCurrently using native rendering.")},
{TEXT("\nこの構成は動的フレーム生成の目標FPS設定に対応していません。保存設定を保持し、生成を停止しています。"), TEXT("\nThis build does not support a target FPS for dynamic frame generation. Generation is paused; your setting is retained.")},
{TEXT("\n案内表示の準備ができないため、フレーム生成を一時停止しています。"), TEXT("\nFrame generation is paused while the HUD is unavailable.")},
{TEXT("\nメニュー中はフレーム生成を一時停止します。探索へ戻ると再開します。"), TEXT("\nFrame generation pauses in menus and resumes during exploration.")},
{TEXT("\nフレーム生成を一時停止しています。"), TEXT("\nFrame generation is paused.")},
{TEXT("\n保存されたフレーム生成設定はこの環境で利用できません。"), TEXT("\nThe saved frame generation setting is unavailable on this system.")},
{TEXT("ネイティブ / TSR 描画を使用しています。\nこの配布版にはDLSS・フレーム生成・Reflexが含まれていません。保存済みの設定は保持されます。"), TEXT("Using Native / TSR rendering.\nThis build does not include DLSS, frame generation or Reflex. Saved preferences are retained.")},
{TEXT("保存フォルダーを作成できません。保存場所の空き容量と権限を確認してください。"), TEXT("Cannot create the save folder. Check free space and folder permissions.")},
{TEXT("保存データを開けませんでした。元のファイルは保持しています。"), TEXT("Cannot open save data. The original file has been preserved.")},
{TEXT("破損した保存データの退避に失敗しました。元のファイルを保持しています。"), TEXT("Cannot move the damaged save file aside. The original file has been preserved.")},
{TEXT("バックアップの復旧に失敗しました。退避した保存データは保持しています。"), TEXT("Backup recovery failed. The saved copy of the original data has been preserved.")},
{TEXT("保存データを前回のバックアップから復旧しました。読み取れなかったファイルも保存フォルダーに保持しています。"), TEXT("Save data restored from the previous backup. The unreadable file has also been preserved in the save folder.")},
{TEXT("新しい版の保存データです。対応するゲームで開いてください。"), TEXT("This save was created by a newer version. Open it with a compatible game version.")},
{TEXT("保存データを準備できません。空き容量と書き込み権限を確認してください。"), TEXT("Cannot prepare save data. Check free space and write permissions.")},
{TEXT("この保存場所には書き込めません。以前の記録は保持しています。"), TEXT("Cannot write to this save folder. Your previous records have been preserved.")},
{TEXT("バックアップ用の一時ファイルを更新できません。"), TEXT("Cannot update the temporary backup file.")},
{TEXT("バックアップを作成できないため保存を見送りました。空き容量と権限を確認してください。"), TEXT("Saving skipped because a backup could not be created. Check free space and permissions.")},
{TEXT("バックアップを検証・更新できませんでした。以前の記録は保持しています。"), TEXT("Cannot verify or update the backup. Your previous records have been preserved.")},
{TEXT("保存データが使用中です。もう一度お試しください。"), TEXT("Save data is in use. Please try again.")},
{TEXT("保存できませんでした。以前の記録は保持しています。空き容量と権限を確認してください。"), TEXT("Could not save. Previous records are preserved. Check free space and permissions.")},
{TEXT("保存する場所の情報が不正です。以前の記録は保持しています。"), TEXT("Invalid location data. Previous records have been preserved.")},
{TEXT("窓辺の記録を読み取る条件が不正です。以前の記録は保持しています。"), TEXT("Invalid window-state query. Previous records have been preserved.")},
{TEXT("窓辺の保存表を確認できませんでした。"), TEXT("Cannot inspect the window-state table.")},
{TEXT("窓辺の記録を読み取れませんでした。"), TEXT("Cannot read the window record.")},
{TEXT("この窓辺の記録は対応する版で開いてください。保存済みの選択は変更していません。"), TEXT("Open this window record with a compatible version. Your saved choice has not changed.")},
{TEXT("水の行き先が不正です。以前の選択は保持しています。"), TEXT("Invalid water destination. Your previous choice has been preserved.")},
{TEXT("発見記録を読み取れませんでした。"), TEXT("Cannot read discovery records.")},
{TEXT("この世界の発見記録が上限に達しました。図鑑から記録を書き出せます。以前の記録は保持します。"), TEXT("This world's discovery limit has been reached. Export records from the journal. Previous records will be preserved.")},
{TEXT("この発見記録が見つかりません。"), TEXT("This discovery record could not be found.")},
{TEXT("記録をまとめられませんでした。"), TEXT("Cannot prepare the records for export.")},
{TEXT("書き出し先を作成できません。"), TEXT("Cannot create the export folder.")},
{TEXT("発見記録-"), TEXT("Discoveries-")},
{TEXT("記録を書き出せませんでした。空き容量と権限を確認してください。"), TEXT("Cannot export records. Check free space and permissions.")},
{TEXT("立つ場所を確認できませんでした。もう一度お試しください。"), TEXT("Could not find a safe place to stand. Please try again.")},
{TEXT("最後の足場へ戻りました。"), TEXT("Returned to the last safe footing.")},
{TEXT("必要な素材を読み込めません。配布ファイルを展開し直してください。"), TEXT("Required assets could not be loaded. Extract the distribution files again.")},
{TEXT("窓辺の素材を読み込めません。配布ファイルを確認してください。"), TEXT("Window assets could not be loaded. Check the distribution files.")},
{TEXT("水都の素材を読み込めません。配布ファイルを確認してください。"), TEXT("Water City assets could not be loaded. Check the distribution files.")},
{TEXT("前回の場所"), TEXT("Previous location")},
{TEXT("窓辺の保存場所を開けません。水の選択は変更していません。"), TEXT("Cannot open the window's save folder. The water setting has not changed.")},
{TEXT("雨継ぎの窓辺　座って街を眺める"), TEXT("Raincatcher Window — Sit and watch the city")},
{TEXT("分水器　水を窓辺へ流す"), TEXT("Water valve — Direct water to the window")},
{TEXT("分水器　水を外樋へ戻す"), TEXT("Water valve — Return water to the outer gutter")},
{TEXT("水の選択を保存できません。以前の流れを保っています。"), TEXT("Cannot save the water setting. Keeping the previous flow.")},
{TEXT("水が窓辺へ流れ始めました。この流れを覚えておきます。"), TEXT("Water is flowing by the window. This setting will be remembered.")},
{TEXT("水を外樋へ戻しました。この流れを覚えておきます。"), TEXT("Water returned to the outer gutter. This setting will be remembered.")},
{TEXT("生活データの保存先を作成できません。"), TEXT("Cannot create the life-data save folder.")},
{TEXT("生活データを開けません。元のファイルを保持しています。"), TEXT("Cannot open life data. The original file has been preserved.")},
{TEXT("生活データを復旧できません。元データとバックアップを保持しています。"), TEXT("Cannot restore life data. The original file and backup have been preserved.")},
{TEXT("生活データを前回のバックアップから復旧しました。読み取れなかったファイルも保存しています。"), TEXT("Life data restored from the previous backup. The unreadable file has also been preserved.")},
{TEXT("新しい版の生活データです。対応するゲームで開いてください。"), TEXT("This life data comes from a newer version. Open it with a compatible game version.")},
{TEXT("生活データを準備できません。"), TEXT("Cannot prepare life data.")},
{TEXT("生活データを検証できないため保存を止めました。"), TEXT("Saving stopped because life data could not be verified.")},
{TEXT("バックアップを作成できないため保存を止めました。空き容量を確認してください。"), TEXT("Saving stopped because a backup could not be created. Check free disk space.")},
{TEXT("保存する設定が不正です。"), TEXT("Invalid setting data.")},
{TEXT("生活データを保存できませんでした。前回の記録を保持しています。"), TEXT("Could not save life data. Previous records have been preserved.")},
{TEXT("釣果の内容を確認できませんでした。"), TEXT("Cannot validate this catch.")},
{TEXT("釣果を確認できません。"), TEXT("Cannot check catch records.")},
{TEXT("同じ釣果番号に異なる記録があるため、保存を止めました。"), TEXT("Saving stopped because this catch ID already has a different record.")},
{TEXT("釣果を保存できません。空き容量を確認して「保存を再試行」を選んでください。"), TEXT("Cannot save this catch. Check free space and choose Retry Save.")},
{TEXT("釣った魚から展示する魚を選んでください。"), TEXT("Choose an exhibit from fish you have caught.")},
