// Display translations only. Stored place names and procedural recipe labels
// remain unchanged so existing saves and world generation keep their identity.
{TEXT("北の水鏡プール"),TEXT("Northern Mirror Pool")},
{TEXT("雲を眺めるプール"),TEXT("Cloudwatch Pool")},
{TEXT("夕凪のプール"),TEXT("Evening Calm Pool")},
{TEXT("屋上庭園・北の水鏡プール"),TEXT("Roof Garden - Northern Mirror Pool")},
{TEXT("屋上庭園・雲を眺めるプール"),TEXT("Roof Garden - Cloudwatch Pool")},
{TEXT("屋上庭園・夕凪のプール"),TEXT("Roof Garden - Evening Calm Pool")},
{TEXT("天空シアター・最上階"),TEXT("Sky Theatre - Rooftop")},
{TEXT("水鏡の聖堂・水辺の広場"),TEXT("Mirrorwater Sanctuary - Waterfront Plaza")},
{TEXT("時計広場・街の回廊"),TEXT("Clock Plaza - City Walkway")},
{TEXT("時計広場駅・水都線"),TEXT("Clock Plaza Station - Water City Line")},
{TEXT("白塔の水都駅・水都線"),TEXT("Water City Station - Water City Line")},
{TEXT("上層線・ホテル／空港方面"),TEXT("Upper Line - Hotel / Skyport")},
{TEXT("天空シアター・大画面と客席"),TEXT("Sky Theatre - Screen and Seating")},
{TEXT("高級ホテル 103・104・107・108号室"),TEXT("Cloud Hotel - Rooms 103, 104, 107, 108")},
{TEXT("高級ホテル 101・102・105・106号室"),TEXT("Cloud Hotel - Rooms 101, 102, 105, 106")},
{TEXT("雲上ホテル駅・シアター／空港方面"),TEXT("Cloud Hotel Station - Theatre / Skyport")},
{TEXT("空中港駅・ホテル／シアター方面"),TEXT("Skyport Station - Hotel / Theatre")},
{TEXT("アウレリア空中港・豪華飛行船の搭乗口"),TEXT("Aurelia Skyport - Sky Yacht Boarding")},
{TEXT("アウレリア空中港・最上階"),TEXT("Aurelia Skyport - Rooftop")},
{TEXT("生活データを開けません。"),TEXT("Cannot open life data.")},
{TEXT("雲上レジデンス 下層　101–102号室"),TEXT("Cloud Residences - Lower Level - Rooms 101-102")},
{TEXT("雲上レジデンス 上層　103–104号室"),TEXT("Cloud Residences - Upper Level - Rooms 103-104")},
{TEXT("雲上レジデンス 下層　105–106号室"),TEXT("Cloud Residences - Lower Level - Rooms 105-106")},
{TEXT("雲上レジデンス 上層　107–108号室"),TEXT("Cloud Residences - Upper Level - Rooms 107-108")},
{TEXT("水路のあと"),TEXT("After the Waterway")},
{TEXT("声のない窓"),TEXT("Windows Without Voices")},
{TEXT("帰り道の灯"),TEXT("Lights on the Way Home")},
{TEXT("水と風の時間"),TEXT("A Time for Water and Wind")},
{TEXT("キーワードかYouTubeのURLを入力してください。"),TEXT("Enter search words or a YouTube URL.")},
{TEXT("モニターから立体音響で再生中"),TEXT("Playing spatial audio from the screen")},
{TEXT("音声の形式を確認しています。"),TEXT("Checking the audio format.")},
{TEXT("音声は停止中です。プレーヤーから再生できます。"),TEXT("Audio is stopped. Press Play in the video player.")},
{TEXT("音声を再生できませんでした。動画を開き直してください。"),TEXT("Audio could not play. Reopen the video to try again.")},
{TEXT("このモニターではYouTubeのページを開けます。"),TEXT("This screen can open YouTube pages.")},
{TEXT("YouTubeを読み込んでいます…"),TEXT("Loading YouTube...")},
{TEXT("動画を選び、プレーヤーの再生ボタンを押してください。"),TEXT("Choose a video and press Play in the player.")},
{TEXT("ページを読み込めませんでした。通信状態を確認して検索し直してください。"),TEXT("The page could not load. Check your connection and search again.")},
{TEXT("動画はWindowsの探索用実行版で利用できます。"),TEXT("Video playback is available in the packaged Windows game.")},
{TEXT("動画用の実行ファイルが見つかりません。"),TEXT("The video browser executable is missing.")},
{TEXT("動画用ブラウザーを起動できませんでした。"),TEXT("The video browser could not start.")},
{TEXT("YouTubeのURLを入力してください。"),TEXT("Enter a YouTube URL.")},
{TEXT("停止しました。検索またはURLの入力で再生できます。"),TEXT("Playback stopped. Search or enter a URL to play another video.")},
{TEXT("動画が消音になっています。「音声を有効にする」で解除できます。"),TEXT("The video is muted. Select Enable Audio to unmute it.")},
{TEXT("動画は一時停止中です。"),TEXT("The video is paused.")},
{TEXT("動画と音声を再生中です。音は部屋のモニターから聞こえます。"),TEXT("Video and audio are playing. Sound comes from the screen in the room.")},
{TEXT("映像を再生中です。音が聞こえない場合は「音声を有効にする」を押してください。"),TEXT("Video is playing. If you cannot hear it, select Enable Audio.")},
