"""Regenerate the complete public yacht, terminal and sky-theatre source set.
Uses the public exterior design; all walking/collision dimensions retain their
original procedural values. Runtime headers are written to SourceArt/Generated
for explicit review, never over the game's source files.
"""
from pathlib import Path
import runpy
globals().update(runpy.run_path(str(Path(__file__).with_name('build_aero87.py'))))
for name,b,note in [('Aero87Hull',hull,'116 m streamlined hollow hull, open deck and swept arches'),
                    ('Aero87Glass',glass,'Panoramic side glazing and transparent observation rail'),
                    ('Aero87Deck',deck,'Teak sun deck with real stair and recessed pool openings'),
                    ('Aero87Interior',interior,'Walkable salon floor, twin 30-step stairways and coffered ceiling'),
                    ('Aero87Furniture',furn,'Library, bar, 12 salon settings, eight pergolas and loungers'),
                    ('Aero87Garden',garden,'Original potted broad-leaf plants'),
                    ('Aero87Water',water,'Recessed swimming-pool surface'),('Aero87Fins',fins,'Volumetric swept fins and four ducted turbine housings')]:
    if name not in ('Aero87Hull','Aero87Fins'):emit(name,b,note)

# New roof cinema: reuse the authored terrace/seating dimensions, omitting every
# piece of the former monolithic screen and its legs. Screen housing is an actor.
source=Path(__file__).with_name('build_city82.py').read_text(encoding='utf8')
terrace=source[source.index('b=B();seats=B()'):source.index('# A slim cantilevered surround')]
ns=dict(B=B,IVORY=IVORY,TEAL=(.025,.22,.23,1),OAK=TEAK,GOLD=GOLD,beam=lambda b,a,c,r,col:beam(b,a,c,r,col=col))
exec(terrace,ns);cinema=ns['b']
for x in [-21.5,21.5]:
    for y in [-15,7]:
        box(cinema,(x,y,.43),(.62,.58,.86),c=DARK)
        for z in [.25,.58]:
            cinema.lathe([(0,0),(.15,0),(.15,.03),(0,.03)],(x,y,z),'Aero87Hull',24,DARK)
    box(cinema,(x,0,.05),(.05,42,.05),'Aero87Glow',(.65,.83,1,1),.01)
emit('SkyTheatre87Deck',cinema,'47 m terrace only: no screen, support legs or braces')

# Terminal is a real rooftop lounge plus a narrow north boarding pier.
b=B()
box(b,(0,0,-.20),(36,36,.40),'Aero87Hull',IVORY,.10)
box(b,(0,26,-.12),(3.5,16,.24),'Aero87Teak',TEAK,.035)
for x in [-16.4,16.4]:
    for y in [-12,12]:
        beam(b,(x,y,0),(x,y,5.1),.18,'Aero87Hull',IVORY)
box(b,(0,0,5.2),(34,28,.28),'Aero87Hull',IVORY,.12)
for x in [-15.8,15.8]:box(b,(x,0,5.04),(.07,26,.055),'Aero87Glow',(1,.69,.36,1),.012)
for x in [-12,12]:
    lounge(b,(x,4,0));lounge(b,(x,-4,0),math.pi);table(b,(x,0,0),True);plant(b,(x,-8,0),1.3,10)
for side in [-1,1]:
    for y in range(18,35,2):beam(b,(side*1.70,y,0),(side*1.70,y,1.12),.04)
    beam(b,(side*1.70,18,1.12),(side*1.70,34,1.12),.05)
label(b,'A U R E L I A   S K Y P O R T',(0,13.98,4.13),.52)
label(b,'PANORAMA CRUISE  /  BOARDING',(0,16.9,2.75),.22)
emit('Aero87Terminal',b,'Rooftop lounge and 16 m north boarding pier; lift access and perimeter rails are fitted to actual tower')

# Compound simple collision is imported as one body, avoiding hundreds of scene
# components being transformed every frame. It is invisible in the game.
stub=B();box(stub,(0,0,-9),(0.02,.02,.02),bevel=0)
emit('Aero87Collision',stub,'Invisible compound collision: decks, stairs, rails, glazing and furniture')
base=bpy.data.objects['SM_Aero87Collision'];base.location=(0,0,0)
bpy.ops.object.select_all(action='DESELECT');base.select_set(True)
for i,c in enumerate(bodies):
    verts,faces=g['beveled_box']([x*.02 for x in c['e']],0)
    r=Matrix.Rotation(math.radians(c['yaw']),3,'Z');p=Vector([x*.01 for x in c['p']])
    v=[tuple(r@Vector(x)+p) for x in verts];v=[(x,-y,z) for x,y,z in v]
    mesh=bpy.data.meshes.new(f'UCX_SM_Aero87Collision_{i:04d}');mesh.from_pydata(v,[],[tuple(reversed(f)) for f in faces]);mesh.update()
    obj=bpy.data.objects.new(mesh.name,mesh);bpy.context.collection.objects.link(obj);obj.select_set(True)
bpy.context.view_layer.objects.active=base
f=OUT/'Meshes/SM_Aero87Collision.fbx'
bpy.ops.export_scene.fbx(filepath=str(f),use_selection=True,object_types={'MESH'},add_leaf_bones=False,bake_anim=False,
    axis_forward='-Y',axis_up='Z',apply_unit_scale=True,global_scale=1,mesh_smooth_type='FACE',use_mesh_modifiers=True,path_mode='AUTO')
import hashlib
records[-1]['sha256']=hashlib.sha256(f.read_bytes()).hexdigest()

(OUT/'aero87-catalog.json').write_text(json.dumps({'revision':87,'public_design_revision':'observatory-barge-v1','assets':records,'collision_boxes':len(bodies)},indent=2),encoding='utf8')
(OUT/'aero87-collision.json').write_text(json.dumps(bodies,indent=2),encoding='utf8')
(OUT/'Generated').mkdir(exist_ok=True)
cpp=['// Generated by SourceArt/Scripts/build_aero87.py, same units as authored FBX.','namespace EWAero87Data {','struct Body { FVector P,E; double Yaw; bool Floor; };','inline TArray<Body> Bodies(){return {']
for v in bodies:
    vec=lambda a:'FVector('+','.join(f'{x:.4f}' for x in a)+')'
    cpp.append('{'+vec(v['p'])+','+vec(v['e'])+f",{v['yaw']:.6f},"+('true' if v['floor'] else 'false')+'},')
cpp+=['};}','}']
(OUT/'Generated/EWAero87Data.inl').write_text('\n'.join(cpp)+'\n',encoding='utf8')

print('AERO87_COMPLETE',len(records),sum(r['triangles'] for r in records),'collision_boxes',len(bodies),flush=True)
