"""Water-edge architecture in centimetres; also exports its native solid plan."""
from pathlib import Path
import json,math,random

IVORY=(.88,.89,.78,1);STONE=(.74,.80,.70,1);PATINA=(.24,.43,.34,1)

def build(plan,groups,mesh,box,beam,foam_patch,out):
    solids=[];plantings=[];rng=random.Random(6409)
    def solid(group,p,d,colour=STONE,bevel=3):
        box('WaterCity'+group+'Stone',p,d,colour,bevel)
        solids.append({'centre':list(p),'extent':[v/2 for v in d]})

    # Broad cornices catch the light, with narrow pilasters beside the flow.
    # The new stone projections are explicitly registered, so even a fall onto
    # a lip has solid support. The open centre has no invisible backing wall.
    for fall in plan['falls']:
        group=fall['group'];name='WaterCity'+group+'Stone'
        x0,x1=fall['x0'],fall['x1'];y=fall['start_y'];top=fall['top_z'];bottom=fall['bottom_z']
        for x in (x0-44,x1+44):
            solid(group,(x,y+30,(top+bottom)/2-55),(64,150,top-bottom+90),IVORY,5)
            solid(group,(x,y+16,top-32),(105,198,64),IVORY,4)
            solid(group,(x,y+15,bottom+16),(100,190,70),STONE,4)
        solid(group,((x0+x1)/2,y+60,top-72),(x1-x0+70,180,58),IVORY,4)
        # Keep the centre open: no backing panels or unsupported cross strips.
        foam_patch(group,(x0+x1)/2,fall['end_y']-48,bottom+5,x1-x0+180,210,0,.73)

    # Asymmetric planted islands preserve the long open water views. They are
    # rooted on the real bed and stay away from the traversable quay footprint.
    islands=[
        ('Central',4770,7000,1950,190,340),
        ('Central',8080,6130,1950,220,470),
        ('Central',5720,9710,1950,240,500),
        ('North',7390,13940,3850,220,360),
        ('North',5430,14490,7450,230,610),
        ('North',7360,15170,7450,240,510),
        ('South',7400,-3190,150,230,440),
        ('South',5390,-2660,150,220,360)]
    leaf_count=0
    for index,(group,x,y,z,w,d) in enumerate(islands):
        name='WaterCity'+group+'Stone'
        solid(group,(x,y,z-120),(w,d,276),STONE,8) # bed -258 to +18
        solid(group,(x,y,z+19.5),(w-32,d-32,3),(.16,.22,.13,1),1)
        for side in (-1,1):
            solid(group,(x+side*(w/2-9),y,z+34),(18,d,32),IVORY,3)
            solid(group,(x,y+side*(d/2-9),z+34),(w-36,18,32),IVORY,3)
        for sy in (-.26,.04,.30):
            plantings.append({'mesh':'FernPatch','position':[x+(-1 if sy<0 else 1)*w*.10,y+d*sy,z+21],
                              'scale':[.54,.64,.95],'yaw':rng.uniform(0,360)})
        # Clusters of upright water iris leaves, modelled as thin closed blades.
        for cluster in range(3):
            px=x+rng.uniform(-w*.20,w*.20);py=y+rng.uniform(-d*.30,d*.30)
            for k in range(11):
                angle=rng.uniform(0,math.tau);height=rng.uniform(90,172);reach=rng.uniform(24,66)
                vertices=[];faces=[]
                for step in range(8):
                    t=step/7;width=5.2*math.sin(math.pi*t)**.7+.12
                    bx=px+math.cos(angle)*reach*t*t;by=py+math.sin(angle)*reach*t*t
                    bz=z+21+height*(t-.12*t*t)
                    for side in (-1,1):
                        vertices.append((bx-math.sin(angle)*width*side,by+math.cos(angle)*width*side,bz))
                vertices += [(vx,vy,vz-.7) for vx,vy,vz in vertices]
                for s in range(7):
                    a=s*2;faces += [(a,a+1,a+3,a+2),(a+18,a+19,a+17,a+16),
                                   (a,a+2,a+18,a+16),(a+1,a+17,a+19,a+3)]
                mesh(name,vertices,faces,'WaterCityStone',(.16+rng.random()*.06,.34+rng.random()*.08,.16,1),smooth=True)
                leaf_count+=1
        # A few lily pads touch the calmer shore; the centre of each pool stays
        # clear. Their raised folded tips stay above the centimetre water waves.
        inward=1 if x<6400 else -1
        for k in range(7):
            px=x+inward*(w/2+55+rng.uniform(0,160));py=y+rng.uniform(-d*.65,d*.65)
            radius=rng.uniform(18,39);yaw=rng.uniform(0,math.tau)
            vertices=[(px,py,z+4)];n=25
            for i in range(n):
                a=yaw+.19+i*(math.tau-.38)/(n-1)
                vertices.append((px+math.cos(a)*radius,py+math.sin(a)*radius,z+4+2*math.sin(i*math.pi/(n-1))))
            mesh(name,vertices,[(0,i,i+1) for i in range(1,n)],'WaterCityStone',(.20,.39,.19,1),smooth=True)
        # A pale submerged shelf creates a legible shallow margin and contact
        # shadow underneath the planting, instead of an island floating on blue.
        solid(group,(x,y,z-125),(w+90,d+90,22),(.58,.68,.55,1),4)

    root=Path(out).parent
    header=['// Generated by water_city_gardens.py. Shared with the visible stone.','#pragma once',
            'namespace EW::WaterGardenData {',
            'struct Solid { FVector Centre, Extent; };','inline const TArray<Solid>& Solids() {',
            'static const TArray<Solid> Values = {']
    def vec(v):return 'FVector('+','.join(f'{x:.5f}' for x in v)+')'
    header += ['{'+vec(s['centre'])+','+vec(s['extent'])+'},' for s in solids]
    header += ['};return Values;}','struct Plant { const TCHAR* Mesh; FVector Position, Scale; double Yaw; };',
               'inline const TArray<Plant>& Plants() {','static const TArray<Plant> Values = {']
    header += ['{TEXT("'+p['mesh']+'"),'+vec(p['position'])+','+vec(p['scale'])+f",{p['yaw']:.5f}"+'},' for p in plantings]
    header += ['};return Values;}','}']
    (root/'Source/EndlessWorld/EWWaterCityGardenPlan.h').write_text('\n'.join(header)+'\n',encoding='utf8')
    result={'revision':3,'planted_islands':len(islands),'iris_blades':leaf_count,'lily_pads':len(islands)*7,
            'solids':solids,'plants':plantings,'framed_falls':len(plan['falls'])}
    (Path(out)/'water-city-gardens.json').write_text(json.dumps(result,indent=2),encoding='utf8')
    return {k:v for k,v in result.items() if k not in ('solids','plants')}
